@node ax_cxx_compile_stdcxx_11
@unnumberedsec ax_cxx_compile_stdcxx_11

@majorheading Synopsis

@smallexample
AX_CXX_COMPILE_STDCXX_11([ext|noext])
@end smallexample

@majorheading Description

Check for baseline language coverage in the compiler for the C++11
standard; if necessary, add switches to CXXFLAGS to enable support.
Errors out if no mode that supports C++11 baseline syntax can be found.
The argument, if specified, indicates whether you insist on an extended
mode (e.g. -std=gnu++11) or a strict conformance mode (e.g. -std=c++11).
If neither is specified, you get whatever works, with preference for an
extended mode.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx_11.m4,latest
version of @file{ax_cxx_compile_stdcxx_11.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_cxx_compile_stdcxx_11.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Benjamin Kosnik @email{bkoz@@redhat.com}} @* @w{Copyright @copyright{} 2012 Zack Weinberg @email{zackw@@panix.com}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
