@node ax_ext
@unnumberedsec ax_ext

@majorheading Synopsis

@smallexample
AX_EXT
@end smallexample

@majorheading Description

Find supported SIMD extensions by requesting cpuid. When an SIMD
extension is found, the -m"simdextensionname" is added to SIMD_FLAGS
(only if compilator support it) (ie : if "sse2" is available "-msse2" is
added to SIMD_FLAGS)

This macro calls:

@smallexample
  AC_SUBST(SIMD_FLAGS)
@end smallexample

And defines:

@smallexample
  HAVE_MMX / HAVE_SSE / HAVE_SSE2 / HAVE_SSE3 / HAVE_SSSE3 /
  HAVE_SSE41 / HAVE_SSE42 / HAVE_AVX
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_ext.m4,latest
version of @file{ax_ext.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_ext.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Christophe Tournayre @email{turn3r@@users.sourceforge.net}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
